services:
  terraform:
    image: hashicorp/terraform:latest
    working_dir: "/workpace"
    volumes:
      - ./:/workpace
      - .aws/:/root/.aws:ro
    environment:
      - TF_VAR_SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - TF_VAR_SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
